server:
  port: 8089
mybatis:
  #指sql语句在配置文件中的情况
  mapper-locations: classpath*:/mappers/*Mapper.xml
  configuration:
    mapUnderscoreToCamelCase: true

spring:
  datasource:
    dynamic:
      #dao没有指定访问哪个数据源，指定默认的数据源
      primary: mysql
      #是否是严格模式，严格模式指dao没有指定数据源，就报错。 非严格模式允许dao不配置数据源，会启动默认数据源进行连接
      strict: false
      datasource:
        #定义了三个数据源，mybatis(mysql)，ck(clickhouse),hbase(hbase)
        mysql:
#          url: jdbc:mysql://172.20.7.167:3307/Mybatis?useSSL=false&useUnicode=true&characterEncoding=UTF-8
          url: jdbc:mysql://36.32.174.69:3306/ad?useSSL=false&useUnicode=true&characterEncoding=UTF-8
          username: root
#          password: "MySQL!23"
          password: "000000"
          driver-class-name: com.mysql.cj.jdbc.Driver
        ck:
#          url: jdbc:clickhouse://172.20.7.167:18123/default
          url: jdbc:clickhouse://36.32.174.72:18123/default
          username: default
          password: Ck18123
          driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
        hbase:
          url: jdbc:phoenix:36.32.174.69,36.32.174.70,36.32.174.71:2181
          username:
          password:
          driver-class-name: org.apache.phoenix.jdbc.PhoenixDriver
  redis:
#    host: 172.20.7.167
    host: 36.32.174.72
    port: 16379
    database: 2
    password: Redis6379

  elasticsearch:
    uris: 36.32.174.117:9200

  kafka:
    bootstrap-servers: 36.32.174.72:19092

